
version: '3.8'

services:
  face-detection:
    env_file:
      - .env
    
    build: 
      context: ../src/app
      dockerfile: Dockerfile
    command: bash -c 'sleep 1; python ./src/app/main.py'
    volumes:
      - ..:/app
    expose:
      - "5000"
    scale: 1
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/test_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
      - PYTHONPATH=/app
    depends_on:
      - db 

  db:
    env_file:
      - .env
    build: 
      context: ../src/db
      dockerfile: Dockerfile
    container_name: pg_container
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
      - PYTHONPATH=/app

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - face-detection
    ports:
      - "4000:4000"

volumes:
  db: