
version: '3.8'

services:
  face-detection:
    env_file:
      - .env
    build: 
      context: ../src/app
      dockerfile: Dockerfile
    command: bash -c 'sleep 20; uvicorn --app-dir=.. app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:password@db:5432/postgres
    depends_on:
      - db
  db:
    env_file:
      - .env
    build:
      context: ../src/db
      dockerfile: Dockerfile
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432

volumes:
  postgres_data:
