
version: '3.3'

services:
  face-detection:
    env_file:
      - .env

    build: 
      context: ../src/app
      dockerfile: Dockerfile
    command: bash -c 'sleep 1; python ./src/app/main.py'
    volumes:
      - ..:/app
    expose: 
      - 8000
    scale: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi1.rule=PathPrefix(`/face/v1`)"
      - "traefik.port=8000"
    depends_on:
      - db 

  app1:
    env_file:
      - .env
    build: 
      context: ../src/app1
      dockerfile: Dockerfile
    command: bash -c 'sleep 1; python ./src/app1/main.py'
    volumes:
      - ..:/app
    expose: 
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi2.rule=PathPrefix(`/text/v1`)"
      - "traefik.port=5000"

  db:
    env_file:
      - .env
    build: 
      context: ../src/db
      dockerfile: Dockerfile
    container_name: pg_container
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
      - PYTHONPATH=/app

  traefik:
    image: traefik
    ports:
      - 8008:80
      - 8081:8080
    volumes:
          - "./traefik.dev.toml:/etc/traefik/traefik.toml"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - face-detection
  #   ports:
  #     - "4000:4000"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
    
volumes:
  db:
  pgadmin-data: