
version: '3.3'

services:
  face-detection:
    env_file:
      - .env
    
    build: 
      context: ../src/app
      dockerfile: Dockerfile
    command: bash -c 'sleep 1; python ./src/app/main.py'
    volumes:
      - ..:/app
    ports:
    - "5000:5000"
    # scale: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.face-detection.rule=Host(`0.0.0.0`)"
      - "traefik.port=5000"
    depends_on:
      - db 

  db:
    env_file:
      - .env
    build: 
      context: ../src/db
      dockerfile: Dockerfile
    container_name: pg_container
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
      - PYTHONPATH=/app

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - face-detection
  #   ports:
  #     - "4000:4000"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
    
  reverse-proxy:
    image: traefik
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--configFile=traefik.toml"
    ports:
      - "8080:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
volumes:
  db:
  pgadmin-data: